### ISSUE TITLE
Some thoughts.

### ISSUE THREAD

**Issue by ermik** [Eclipse-/EclipseUI#10]
As a healer:

I like when I really get visual representation oh HP, black HP bar going down on black backgrund especially in small raid frames doesn't give me that.

Not a lot of people want to see loot master icon on their raid frame, some creative design for it and maybe for raid leader icon would be cool.

Group Role icons are just junk on raid frames. I suggest making them mouseover or key-hold visible.

There is a config module for tukui. I suggest, if my judgement is right upon how much work you've really done, to rewrite/improve it. It won't take much time compare to the whole UI.

How do I move focus frame? It seems to be under my raid frames.

**Comment by Eclipse-** [comment]
Thank you for the comments ermik.

I do always appreciate the feedback I get and try to incorporate it in some ways; if I can see other users benefiting from said ideas.

Concerning the visual representation of the health bars on the raid frames, it is freely change-able to whatever you want in the config file. However, I may plan to add an extra option to the health bars, such as gradient health values instead of just class-coloured or not. Either way, colours will always be change-able by the user.

The raid/party frame icons have not been touched at all by myself yet. I personally hate icons and the ML/Leader icons will soon disappear once I start work on the frames again. I'll see if I can come up with some nifty ideas for the group-role icons though ;)

I understand a lot of Tukui users have now become accustomed to using the In-Game Configuration, and don't get me wrong it's a great tool for people who don't want to dabble in the Lua files, but for me it's something I will never use. Of course that's not to say I won't support it, because I have done in previous releases; I just feel it leaves a little to be desired. I've thought about writing my own In-Game Configuration and if I get round to doing it, then it will be done, but that won't be for a while yet.

**Comment by Eclipse-** [comment]
To move the focus frame, go into the unitframes folder and open layout.lua and find this

"focus:SetPoint("TOP", UIParent, "BOTTOM", 0, TukuiDB.Scale(230))"

There's 2 instances of this code and you'll want the one that's inside this

"if addon == "TukuiHeal" then"

**Comment by ermik** [comment]
Okay, thanks for help with focus, I now understand:  just gonna dig a bit of lua code, not a big deal. Bu you DO NEED to change focus frame Default position for future releases. Not everyone have my eyes to see it behind raid frames.

Alpha release is awsome so far, your work-around for showing and hiding action bars is damn inzane, luv it. Did you think about making some block option for this functionality to prevent accidential toggles? Or lua again?

Thanks.

**Comment by Eclipse-** [comment]
I agree the focus placement is shitty, I just forgot to change it when I was setting up the healing raid frames. Should be fixed when I push tomorrow :)

At the moment I've just put a few basic things in place to get the wheels rolling, but majority of my time is currently dedicated to the design side of the UI for now. However, with saying that I think I've finally got to somewhere I like with the amount of hours I spent just looking at the UI today, aha.

Nice suggestion about the accidental toggles though, I can completely understand where you're coming from on this one. Would be such a pain to always accidentally toggle your bars or to do it outside of combat and then get thrown into combat. I guess a simple lock/unlock command or toggle button should suffice :)

**Comment by ermik** [comment]
What I don't like about tukui focus unit is its castbar mechanism. For instance, if I use focus to throw Becaon of Light on myself I really have no intention to see 1 more cast bar of my spells. 

There should be some digestive thing that adjusts to what your focus target is.

I think it's normal that this issue is closed. Have no idea how git works these days...

**Comment by ermik** [comment]
Castbars in LUAs have no separated position config. setPoints are in main definition blocks. Sucks =(
